version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: mk123456
      POSTGRES_DB: phuonggiang
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   networks:
  #     - postgres
  #   env_file:
  #     - ./frontend/.env

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - postgres
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=docker

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: