version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    networks:
      - postgres