export const variables = {
  // Layout Form
  LAYOUT_FORM_VERTICAL: 'vertical',
  LAYOUT_FORM_HORIZONTAL: 'horizontal',
  // TYPE FORM
  INPUT: 'input',
  INPUT_PASSWORD: 'inputPassword',
  PRICE: 'price',
  PERCENT: 'percent',
  INPUT_SEARCH: 'inputSearch',
  SELECT: 'select',
  SELECT_ADD: 'selectAdd',
  SELECT_MUTILPLE: 'selectMutilple',
  SELECT_TAGS: 'tags',
  CASCADER: 'cascader',
  TEXTAREA: 'textArea',
  RANGE_PICKER: 'rangePicker',
  TIME_RANGE: 'timeRange',
  TIME_PICKER: 'timePicker',
  TREE_SELECT: 'treeSelect',
  TREE_SELECT_ADD: 'treeSelectAdd',
  TREE_SELECT_SINGLE: 'treeSelectSingle',
  DATE_PICKER: 'datePicker',
  MONTH_PICKER: 'monthPicker',
  WEEK_PICKER: 'weekPicker',
  MONTH_YEAR_PICKER: 'monthYearPicker',
  YEAR_PICKER: 'yearPicker',
  DATE_TIME_PICKER: 'dateTimePicker',
  CHECKBOX: 'checkbox',
  CHECKBOX_SINGLE: 'checkboxSingle',
  CHECKBOX_FORM: 'checkboxform',
  RADIO: 'radio',
  INPUT_NUMBER: 'inputNumber',
  INPUT_NOTE: 'inputNote',
  INPUT_COUNT: 'inputCount',
  INPUT_DATE: 'inputDate',
  INPUT_MONEY: 'inputMoney',
  SWITCH: 'switch',
  AUTO_COMPLETE: 'AutoComplete',
  INPUT_PROJECT: 'inputProject',
  // RULES
  RULES: {
    EMPTY: { required: true, message: 'Vui lòng không được để trống trường này' },
    EMPTY_INPUT: {
      required: true,
      whitespace: true,
      message: 'Vui lòng không được để trống trường này',
    },
    WHITESPACE: {
      message: 'Vui lòng không được để trống trường này',
      whitespace: true,
    },
    MAX_LENGTH_INPUT_CODE: { max: 30, message: 'Trường này không quá 30 kí tự' },
    MAX_LENGTH_INPUT: { max: 500, message: 'Trường này không quá 500 kí tự' },
    MAX_LENGTH_TEXTAREA: { max: 1000, message: 'Trường này không quá 1000 kí tự' },
    MAX_LENGTH_INPUT_MONTH: {
      type: 'number',
      min: 0,
      max: 12,
      message: 'Trường này tối đa 12',
    },
    MIN_LENGTH_INPUT: { type: 'number', min: 1, message: 'Trường này tối thiểu 1' },
    MIN_DECIMAL_INPUT: {
      min: 1,
      message: 'Trường này là chỉ nhập số nguyên và lớn hơn 0',
    },
    MAX_LENGTH_INPUT_DATE: {
      type: 'number',
      min: 0,
      max: 365,
      message: 'Số ngày không được quá 12 tháng',
    },
    // TODO: Rename
    MAX_LENGTH_15: { max: 15, message: 'Trường này không quá 15 kí tự' },
    MAX_LENGTH_50: { max: 50, message: 'Trường này không quá 50 kí tự' },
    MAX_LENGTH_255: { max: 255, message: 'Trường này không quá 255 kí tự' },
    MAX_LENGTH_250: { max: 250, message: 'Trường này không quá 250 kí tự' },
    MAX_LENGTH_500: { max: 500, message: 'Trường này không quá 500 kí tự' },
    MAX_LENGTH_1000: { max: 1000, message: 'Trường này không quá 1000 kí tự' },
    MAX_LENGTH_100: { max: 100, message: 'Trường này không quá 100 kí tự' },
    MAX_NUMBER: { max: 15, message: 'Trường này không quá 15 kí tự' },
    NUMBER: { pattern: /^[1-9]\d*$/, message: 'Trường này là chỉ nhập số nguyên và lớn hơn 0' },
    CMND: { pattern: /^\d+$/, message: 'Trường này là chỉ là số CMND' },
    NEGATIVE_NUMBER: { pattern: /^-\d*\.?\d+$/, message: 'Trường này chỉ là số dương' },
    EMAIL: { type: 'email', message: 'Trường này là email', required: true },
    EMAIL_SPECIAL_CHARACTER: {
      pattern: /^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@/,
      message: 'Trường này là email',
    },
    SCHOOL_YEARS: {
      pattern: /^[0-9.-]*$/,
      message: 'Năm học chỉ có nhập được số và ký tự gạch ngang',
    },
    PHONE: {
      pattern: /(84|0[2|3|5|7|8|9])+([0-9]{7,8})\b/g,
      message: 'Trường này là số điện thoại',
    },
    YEAR_FROM: 'Từ Năm không được lớn hơn Đến Năm',
    YEAR_TO: 'Đến Năm không được nhỏ hơn Từ Năm',
    INVALID_DATE: 'Ngày không hợp lệ',
    WHITE_SPACE: {
      pattern: /^\S+(?:\s+\S+)*$/,
      message: 'Không được nhập các ký tự khoảng trắng liên tiếp nhau',
    },
    NONE_WHITE_SPACE: {
      pattern: /^\S*$/,
      message: 'Không được nhập ký tự khoảng trắng',
    },
    PASSOWRD_FORMAT: {
      pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()\-_=+{};:,<.>]).{7,}$/,
      message:
        'Mật khẩu có 7 ký tự trở lên và có ít nhất một chữ hoa, một chữ thường, một ký tự đặc biệt',
    },
  },
  // PAGINATION
  PAGINATION: {
    PAGE: 1,
    PAGE_SIZE_SMALL: 5,
    PAGE_SIZE: 10,
    PAGE_SIZE_100: 100,
    PAGE_SIZE_500: 500,
    SIZEMAX: 1000,
    PAGE_SIZE_OPTIONS: ['10', '20', '50', '100'],
    SHOW_SIZE_CHANGER: true,
    PER_PAGE_TEXT: '/ trang',
  },
  // DATE FORMAT
  DATE_FORMAT: {
    DATE_ENG: 'YYYY-MM-DD hh:mm',
    DATE: 'DD-MM-YYYY',
    DATE_TIME: 'DD-MM-YYYY, HH:mm',
    FULL_DATE_TIME: 'DD-MM-YYYY, HH:mm',
    TIME_DATE: 'HH:mm, DD-MM-YYYY',
    TIME_DATE_MONTH: 'HH:mm, DD/MM',
    TIME_DAY_FULL: 'HH:mm, DD/MM/YYYY',
    YEAR: 'YYYY',
    MONTH: 'MM',
    DATE_AFTER: 'YYYY-MM-DD',
    HOUR: 'HH:mm',
    TIME_FULL: 'HH:mm:ss',
    DAY_NAME: 'ddd',
    WEEKLY: 'weekly',
    // TODO: rename
    DATE_VI: 'DD/MM/YYYY',
    TIME_DATE_VI: 'HH:mm, DD/MM/YYYY',
    DATE_TIME_UTC: 'YYYY-MM-DD[T]HH:mm:ss[Z]',
    DATE_MONTH: 'DD/MM',
    SHOW_FULL_DATE: 'dddd - DD/MM/YYYY',
    MONTH_FULL: '[Tháng] MM/YYYY',
    MONTH_NAME: '[Tháng] MM',
    MONTH_YEAR: 'MM/YYYY',
    YEAR_MONTH_DAY: 'YYYY/MM/DD',
    ONLY_DATE: 'D',
    ONLY_MINUTES: 'mm',
    WEEK: 'W',
    SHORT_HOUR: 'H:mm',
  },
  PARENT_ID: '00000000-0000-0000-0000-000000000000',
  SYMBOL: 'xem thêm',
  STATUS_204: 204,
  STATUS_400: 400,
  STATUS_401: 401,
  STATUS_403: 403,
  STATUS_404: 404,
  STATUS_500: 500,
  QUERY_STRING: 'queryString',
  EMPTY_DATA_TEXT: 'Chưa có dữ liệu',
  DAY_OF_WEEKS: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  DAY_OF_WEEK_SHORT: ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'],
  DAY_OF_WEEK: {
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
  },
  DAY_OF_WEEKS_TEXT: {
    Monday: 'Thứ 2',
    Tuesday: 'Thứ 3',
    Wednesday: 'Thứ 4',
    Thursday: 'Thứ 5',
    Friday: 'Thứ 6',
    Saturday: 'Thứ 7',
    Sunday: 'Chủ nhật',
  },
  DAY_OF_WEEKS_TEXT_VI: {
    Monday: 'Thứ hai',
    Tuesday: 'Thứ ba',
    Wednesday: 'Thứ tư',
    Thursday: 'Thứ năm',
    Friday: 'Thứ sáu',
    Saturday: 'Thứ bảy',
    Sunday: 'Chủ nhật',
  },
  NO_DATA: 'Không có dữ liệu',
  REGEX_NUMBER: /\B(?=(\d{3})+(?!\d))/g,
  LABEL_GENDER: {
    FEMALE: 'FEMALE',
    MALE: 'MALE',
  },
  ARRAY_GENDER: [
    { value: 'male', label: 'Nam' },
    { value: 'female', label: 'Nữ' },
  ],
  PATHS: {
    QUAN_LY_DANG_NHAP: '/quan-ly/dang-nhap',
    DANG_NHAP: '/dang-nhap',
  },
};
