name: Deploy api

on:
  push:
    branches: ["main"]

jobs:
  deploy_api:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into Ubuntu Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Clone the repository if not already cloned
            if [ ! -d "phuoggiang-clone" ]; then
              git clone https://github.com/nd-thuong/phuoggiang-clone.git
            fi

            cd phuoggiang-clone/backend

            npm install
            npm run build
            npm run start:prod
